#version 460

#define EHJ_BINDLESS_TEX 1

#if EHJ_BINDLESS_TEX
#extension GL_ARB_bindless_texture : require
#endif

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

#include "../bvh/bvhTraverse.glsl"

layout (std430, binding = 0) readonly buffer I0 { BVHNode node[]; } nodeData;
layout (std430, binding = 1) readonly buffer I1 { uint idx[]; } idxData;
//layout (std430, binding = 2) readonly buffer I2 { vec4 tri[]; } triData;

//struct RRRT_vertex { // rasterizer RT shared vertex
//	vec3 p;
//	float n[3];
//	float uv[2];
//	float tan[4];
//};

struct RRRT_vertex { // rasterizer RT shared vertex
	vec4 p;
	vec4 n;
	vec4 uv;
	vec4 tan;
};

layout(std430, binding = 2) readonly buffer I2 {
	RRRT_vertex tri[];
} triData;

//layout(std430, binding = 2) readonly buffer I2 {
//	vec4 tri[];
//} triData;

DEFINE_TRAVERSE_FUNCTION(
	traverse_ailalaine,
	nodeData.node,
	idxData.idx,
	triData.tri,
	.p.xyz
)

layout (std430, binding = 3) readonly buffer I3 { uint id[]; } matData;

layout(rgba32f, binding = 0) writeonly uniform image2D u_outImg;

uniform vec2 u_resolution;
uniform mat4 u_m;
uniform mat4 u_invVP;
uniform vec3 u_cPos;
uniform float u_time;

uniform float u_frame;
uniform float u_camChange;
layout(binding=0) uniform sampler2D u_p;
layout(binding=1) uniform sampler3D u_blueNoiseTex;
uniform vec3 u_blueNoiseSize;


//// texture stuff
#if EHJ_BINDLESS_TEX
layout(binding = 4,std430) readonly buffer I4 {
	sampler2D u_SceneTextures[];
};
#else
uniform sampler2D u_SceneTextures[80]; // cant use layout binding
#endif
uniform mat3 u_imtn;

//// texture stuff

// acc stuff
uniform mat4 u_prevVP;
// acc stuff

vec3 alu_normalize(vec3 v) {
	float dot_product = dot(v, v);
	
	// Fallback check to prevent division-by-zero on completely empty vectors
	//if (dot_product < 0.000000001) return vec3(0.0); 
	
	// 0x5f3759df Fast Inverse Square Root
	float xhalf = 0.5 * dot_product;
	int i = floatBitsToInt(dot_product);
	i = 0x5f3759df - (i >> 1); 
	float f = intBitsToFloat(i);
	f = f * (1.5 - xhalf * f * f); // Precision pass
	
	return v * f;
}

//#include "../rand.glsl" // too slow for this

//TODO theorized that passing structs could be slower?
//TODO test if this is actually faster then just passing the corresponding RRRT_vertex
vec2 getUV(uint vId) {
	return triData.tri[vId].uv.xy;
	//return vec2(
	//	triData.tri[vId].uv[0],		
	//	triData.tri[vId].uv[1]
	//);
}
vec3 getTAN(uint vId) {
	return triData.tri[vId].tan.xyz;
	//return vec3(
	//	triData.tri[vId].tan[0],
	//	triData.tri[vId].tan[1],
	//	triData.tri[vId].tan[2]
	//);
}

vec3 getNormal(float hitTriIdx) {
	uint triIdx = floatBitsToUint(hitTriIdx);
	uint v0 = triIdx * 3;
	vec3 edge1 = triData.tri[v0 + 1].p.xyz - triData.tri[v0].p.xyz;
	vec3 edge2 = triData.tri[v0 + 2].p.xyz - triData.tri[v0].p.xyz;

	return alu_normalize(cross(edge1.xyz, edge2.xyz));
}

vec3 getNormal(uint triIdx) {
	uint v0 = triIdx * 3;
	vec3 edge1 = triData.tri[v0 + 1].p.xyz - triData.tri[v0].p.xyz;
	vec3 edge2 = triData.tri[v0 + 2].p.xyz - triData.tri[v0].p.xyz;

	return alu_normalize(cross(edge1.xyz, edge2.xyz));
}

vec2 getUVlerp(uint triIdx, vec2 uv) {
	uint v0 = triIdx * 3u;
	vec2 uv0 = getUV(v0);
	vec2 uv1 = getUV(v0 + 1u);
	vec2 uv2 = getUV(v0 + 2u);

	float w = 1.0 - uv.x - uv.y;
	vec2 interpolatedUV = (uv0 * w) + (uv1 * uv.x) + (uv2 * uv.y);

	return interpolatedUV;
}

vec3 getTANlerp(uint triIdx, vec2 uv) {
	uint v0 = triIdx * 3u;
	vec3 tan0 = getTAN(v0);
	vec3 tan1 = getTAN(v0 + 1u);
	vec3 tan2 = getTAN(v0 + 2u);

	float w = 1.0 - uv.x - uv.y;
	vec3 interpolatedTAN = (tan0 * w) + (tan1 * uv.x) + (tan2 * uv.y);

	return interpolatedTAN;
}

float hash3(vec3 p) {
	p = fract(p * vec3(443.8975, 441.4230, 437.1951));
	p += dot(p, p.yzx + 19.19);
	return fract((p.x + p.y) * p.z);
}

vec3 random_in_unit_sphere(vec3 seed) {
	float h1 = hash3(seed);
	float h2 = hash3(seed + 1.0);
	float h3 = hash3(seed + 2.0);
	vec3 p = vec3(h1, h2, h3) * 2.0 - 1.0;
	return normalize(p);
}

vec3 getBlueNoise(vec2 uv, float bounce) {
	// get exact px coord across screen space bounds
	// wrap coordinates around
	ivec2 pixelCoord = ivec2(mod((uv * u_resolution),(u_blueNoiseSize.xy)));
	
	// animate through depth slices each frame
	int zSlice = int(mod(u_frame+bounce,(u_blueNoiseSize.z)));
	
	// use texelFetch for raw data to avoid float lerp
	vec3 baseNoise = texelFetch(u_blueNoiseTex, ivec3(pixelCoord, zSlice), 0).rgb;
	
	// distribute noise cleanly per bounce using Golden Ratio fractional
	float seed = float(u_frame) + float(bounce) * 13.123; 
	
	baseNoise.x = fract(baseNoise.x + seed * 0.6180339887498949); // Golden Ratio
	baseNoise.y = fract(baseNoise.y + seed * 0.2469796037174670); // Plastic Constant / Silver Ratio variant
	baseNoise.z = fract(baseNoise.z + seed * 0.1591549430918953); // 1/2pi variant
	
	return baseNoise;
}

struct Ray {
	vec3 o;
	vec3 d;
};

// traverse_ailalaine -> (dist,u,v,triIdx)
vec3 shade(Ray r, int iter, vec2 uv, out float primHitdist) {
	vec3 c = vec3(1.0); // Path throughput (starts at pure white)
	vec3 e = vec3(0.0); // Accumulated emission (final color)

	primHitdist = -1.;

	Ray rr = r;
	int bounces = 3;
	bool firstBounce = true;

	for (int i = 0; i < bounces; ++i) {
		// Find the closest geometry hit
		vec4 hit = traverse_ailalaine(rr.o, rr.d, vec3(1.0) / rr.d, 1e30f);
		if (firstBounce && !(hit.x < 1e30f)) {
			e= vec3(0.5, 0.7, 0.9) * 10.; // sky color
			break;
		} else if (i==0) {
			primHitdist = hit.x;
		}

		// Setup hit surface parameters
		vec3 pos = rr.o + hit.x * rr.d;
		vec3 n;
		uint triIdx = floatBitsToUint(hit.w);
		
		vec3 nt = getNormal(triIdx); // triangle normal
		vec2 texUV = getUVlerp(triIdx, hit.yz);
#if 0 // triangle normal
		n = nt;
#endif
#if 1 // texture normal
		{
			vec3 vTan = getTANlerp(triIdx, hit.yz);
			vec3 vNrm = nt;

			// using standardized normalize here costs 280ms!
			vec3 T = alu_normalize(u_imtn * vTan); // requires normalize if model is scaled unevenly
			vec3 N = alu_normalize(u_imtn * vNrm); // requires normalize if model is scaled unevenly
			vec3 B = cross(N, T);

			uint texId = matData.id[triIdx * 3 + 1];

			//TODO textureLod at lvl 0 here could be better to avoid derviative calc?
			vec3 tangentNormal = texture(u_SceneTextures[texId], texUV).xyz * 2.0 - 1.0;

			n = alu_normalize(T * tangentNormal.x + B * tangentNormal.y + N * tangentNormal.z); // normalize for correctness
		}
#endif
		
		vec3 mc = vec3(1.);  // Material Color (Albedo)
		//{
		//	uint triIdx = floatBitsToUint(hit.w);
		//	mc = vec3(triData.tri[triIdx].uv,1.);
		//}
		if (true) {
			vec4 a = texture(u_SceneTextures[matData.id[triIdx*3]],texUV);
			
			//a.rgb = pow(a.rgb,vec3(2.2/1.0));
			//TODO can do srgb -> linear on tex using GL_SRGB8_ALPHA8 instead of GL_RGBA8

			mc = a.rgb;
			if (a.w == 0.) {
				rr = Ray(pos + rr.d * 0.001, rr.d);
				continue;
			}
		}

		firstBounce = false;
		// geometry miss, sample sky
		if (!(hit.x < 1e30f)) {
			e += c * mc * vec3(0.5, 0.7, 0.9) * 10.;
			break; 
		}

		vec3 me = vec3(0.0);  // Material Emission (Glow)
		float roughness = 1.; // 1 = Diffuse, 0 = Mirror
		{
			vec2 m=texture(u_SceneTextures[matData.id[triIdx*3+2]],texUV).gb;
			//m = roughness, metallic
			roughness=m.x;
			//metallic=m.y;
		}

		// Accumulate surface self-emission
		e += c * me;

		// assemble rand vec
		//vec3 seed = pos + n * 1.4142 + vec3(uv, float(i)) * 2.7182 + vec3(float(iter), u_time, -float(iter));
		vec3 noiseVec = getBlueNoise(uv, float(i+iter*bounces));
		vec3 rv = random_in_unit_sphere(noiseVec); 

		//TODO here importance sampling
			// At every single bounce, explicitly trace a shadow ray directly toward a random point on your light sources.
		// NEE NEXT EVENT ESTIMATION (Explicit Sun Shadow Ray):
		vec3 shadowOrigin = pos + nt * 0.001;  // offset to avoid self intersec
		
		
#if 1
		vec3 sunDir = normalize(vec3(.4, 1., -0.2));

		{ // approx area sun
			sunDir = normalize(sunDir + rv*.01);
		}
		//vec3 sunDir = normalize(vec3(.4, 1., -0.3));
		//vec3 sunDir = normalize(vec3(0.,1.,0.));
		vec4 shadowHit;// = traverse_ailalaine(shadowOrigin, sunDir, vec3(1.0) / sunDir, 1e30f);
		for (int j = 0; j < bounces; ++j) {
			shadowHit = traverse_ailalaine(shadowOrigin, sunDir, vec3(1.0) / sunDir, 1e30f);
			if (!(shadowHit.x < 1e30f)) // hit sun
				break;
			uint triIdx2 = floatBitsToUint(shadowHit.w);
			vec2 texUV2 = getUVlerp(triIdx2, shadowHit.yz);
			float a = texture(u_SceneTextures[matData.id[triIdx2*3]],texUV2).a;
			if (a > .1)
				break;
			shadowOrigin = shadowOrigin + sunDir*shadowHit.x;
		}
		
		if (!(shadowHit.x < 1e30f)) {
			// No occlusion: The sun directly illuminates this point
			float cosTheta = max(0.0, dot(n, sunDir));
			vec3 sunIntensity = vec3(10.0);
			
			// Direct lighting = throughput * material color * light * cosine law
			e += c * mc * sunIntensity * cosTheta * vec3(1.,0.9,0.7);

			// TODO on IBL clamp e to 20 avoid fireflies, introduces bias but improves convergence
		}
#endif

		// INDIRECT LIGHTING (Calculate next ray direction):

		vec3 diffuseDir = alu_normalize(n + rv);
		vec3 specDir = reflect(rr.d, n);
		
		vec3 nextDir;
#if 0 // specular seperation
		// STOCHASTIC BLENDING: Instead of mixing vectors, randomly pick path
		// cheap pseudo-random float derived from seed
		//float chooseDiffuse = fract(sin(seed.y * 12.9898) * 43758.5453);
		float chooseDiffuse = noiseVec.y;
		if (chooseDiffuse < roughness) {
			nextDir = diffuseDir;
			c *= mc; // Diffuse surfaces absorb light based on their color
		} else {
			nextDir = specDir;
			// c *= vec3(1.0); // Pure mirrors don't tint the light (unless metal)
		}
#endif
#if 1 // glossy
		nextDir = diffuseDir*roughness + (1.-roughness)*specDir;
		c *= mc;
#endif

		// Update the ray for the next bounce iteration
		rr = Ray(pos + nt * 0.001, nextDir);

		{ // RUSSIAN ROULETTE (Early Termination):
			// If the path gets too dark, statistically kill it to save GPU cycles
			float p = max(c.x, max(c.y, c.z));
			p = clamp(p, 0.05, 0.95); // Essential safety clamp to prevent infinite division (1/0)

			// Kill ray rand num exceeds brightness percentage
			if (noiseVec.z > p) {
				break;
			}

			// Boost surviving rays to maintain energy conservation
			c /= p;
		}
	}

	return e;
}

void main() {
	if (u_frame < 0.)
		return;

	vec2 uv = (vec2(gl_GlobalInvocationID.xy)+.5)/u_resolution.xy;
	ivec2 texelCoord=ivec2(gl_GlobalInvocationID.xy);

	ivec2 imgSize = imageSize(u_outImg);
	if (texelCoord.x >= imgSize.x || texelCoord.y >= imgSize.y) {
		return;
	}
	vec2 ndc = uv * 2.0 - vec2(1.0);
	mat4 invModel = inverse(u_m);

	// campos
	vec3 campos; {
		campos = u_cPos;
		campos = (invModel * vec4(u_cPos, 1.0)).xyz;
	}

	// camdir
	vec3 camdir; {
		vec4 targetWorld = u_invVP * vec4(ndc.x, ndc.y, -1.0, 1.0);
		targetWorld /= targetWorld.w; // Perspective divide
		camdir = alu_normalize(targetWorld.xyz - u_cPos);
		camdir = alu_normalize((invModel * vec4(camdir, 0.0)).xyz);
	}

	vec4 color = vec4(vec3(0.),1.);

#if 0 // direct test
	{	// (dist, u, v, triIdx)
		vec4 hit = traverse_ailalaine( campos, camdir, vec3(1.)/camdir, 1e30f );
		
		//vec4 color = vec4(float(floatBitsToUint(hit.w))*0.00001,0.,0.,1.);
		color = vec4(hit.y,hit.z,0.,1.);

		vec3 n = getNormal(hit.w);
		color = vec4(n,1.);
	}
	// single shadow bounce
	//if (hit.x < 1e30f) {	// bounce
	//	vec3 hitPos = hit.x * camdir + campos + n *0.1;
	//	vec3 sunPos = vec3(0.,10.+sin(u_time)*9.,0.)*100.;
	//	vec3 sunDir = normalize(sunPos-hitPos);

	//	color = vec4(vec3(dot(n,sunDir)),1.);

	//	vec4 hit2 = traverse_ailalaine( hitPos, sunDir, vec3(1.)/sunDir, 1e30f );
	//	if (hit2.x < length(sunPos-hitPos))
	//		color.xyz *= 0.;
	//}
#endif

#if 0 // single
	{
		Ray r;
		r.o=campos;
		r.d=camdir;
		//color = vec4(shade(r,1,uv),1.);
		color.xyz = vec3(0.);
		for (int i=0;i<3;++i)
			color.xyz += shade(r,i,uv);
		color = vec4(color.xyz,1.)*.1 + .9*texture(u_p,uv);
	}
#endif

#if 1 // accumulate
	int samples = 1;
	vec3 c = vec3(0.);
	Ray r;
	r.o=campos;
	r.d=camdir;
	float _;
	for (int i=0;i<samples;++i)
		c += shade(r,i,uv,_);
	c /= samples;
	//color.rgb = c;

	if (u_frame==0)
		color = vec4(c,1.);
	else {
		if (u_camChange == 0.) {
			color = vec4(c,1.) + texture(u_p,uv); // more stable for offline rendering
			//float w = 1./(1.+u_frame);
			//color = vec4(c,1.)*w + (1.-w)*texture(u_p,uv);

			color.a = 1.;
		}
		else 
			color = vec4(c,1.)*.5+.5*texture(u_p,uv);
	}
#endif

	imageStore(u_outImg,texelCoord,color);
}
