#version 460
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

uniform float u_time;
uniform float u_frame;
uniform vec2 u_resolution;

uniform float u_camChange; // 1 on camera Change

uniform mat4 u_m;
uniform vec3 u_cPos;

layout(binding=0) uniform sampler2D u_p;
layout(rgba32f, binding = 0) writeonly uniform image2D u_outImg;

//iq
vec2 sphIntersect( in vec3 ro, in vec3 rd, float ra ) {
	float b	= dot( ro, rd );
	float c	= dot( ro, ro )	- ra*ra;
	float h	= b*b -	c;
	if(	h<0.0 )	return vec2(-1.0); // no intersection
	h =	sqrt( h	);
	return vec2( -b-h, -b+h	);
}

struct Ray {
	vec3 o;
	vec3 d;
};

struct Hit {
	int id;
	float dist;
};

struct Sphere {
	vec3 p;
	float s;
	vec3 col;
	float e; // emission
	float r; // reflection 0 diff, 1 spec
		//TODO seperate color for specular bounce
	vec2 t; // transmission, ior
};

const int sphereCount = 7;
Sphere spheres[sphereCount] = {
	//p			  s		col				e  r   t
	{{3.,2.,0.},  1.,	{1.,1.,1.}	   ,1.,0.,{0.,0.}},
	//{{3.,2.,0.},	.5,   {1.,1.,1.}	 ,0.,0.,{0.,0.}},

	{{0.,0.,0.},  1.,	{0.1,1.,0.1}   ,.2,1.,{0.,0.}},

	{{0.,.5,3.},  .5,	{0.1,0.1,1.}   ,1.,.5,{0.,0.}},
	//{{0.,.5,3.},	.5,   {0.1,0.1,1.}	 ,0.,.5,{0.,0.}},

	{{2.,0.,3.},  1.,	{1.,1.,1.}	   ,0.,0.,{0.,0.}},
	{{0.,-100.,0.},100., {1.,1.,1.}    ,0.,0.,{0.,0.}},
	{{0.,1.,2.},  .5, {1.,1.,1.}	   ,0.,.1,{0.,0.0}},
	{{5.,.75,5.},  1., {1.,1.,1.}		,0.,.1,{0.,0.0}},

	//{{3.,0.,0.},{2.,2.,2.},{1.,1.,1.}		,0.,1.},
	//{{0.,1.,0.},{1.,1.,1.},{0.1,1.,0.1}	,0.,0.},
	//{{0.,1.,3.},{1.,1.,1.},{0.1,0.1,1.}	,0.,.5},
	//{{2.,1.,3.},{1.,1.,1.},{1.,1.,1.}		,0.,.9},
	//{{1.,2.5,1.},{100.,1.,100.},{1.,1.,1.},0.,1.},
};

struct Light {
	vec3 p;
};

Light lights[1] = {
	{{1.,2.,1.}},
};

vec3 CAMPOS = vec3(0.);
vec3 CAMDIR = vec3(0.);
vec2 UV = vec2(0.);

Hit traceTrans(Ray r) {
	// get closest hit
	int closestHit = -1;
	float closestHitDist = 1./0.;

	for (int i=0;i<sphereCount;++i) {
		vec3 center = -spheres[i].p;
		float s = spheres[i].s;
		//vec2 hit = explCircle((r.o+center)/s,r.d/s,1.);
		vec3 p=(r.o+center);
		vec3 d= r.d;
		vec2 hit = sphIntersect(p,d,s);

		if (hit.y >= 0. && hit.x >= 0.) {
			if (closestHit == -1 || closestHitDist > hit.x) {
				closestHitDist = hit.x;
				closestHit = i;
				continue;
			}
		} else if (hit.y >= 0.) {
			closestHitDist = hit.y;
			closestHit = i;
			break;
		}
	}

	return Hit(closestHit,closestHitDist);
}

Hit trace(Ray r) {
	// get closest hit
	int closestHit = -1;
	float closestHitDist = 1./0.;

	for (int i=0;i<sphereCount;++i) {
		vec3 center = -spheres[i].p;
		float s = spheres[i].s;
		//vec2 hit = explCircle((r.o+center)/s,r.d/s,1.);
		vec3 p=(r.o+center);
		vec3 d= r.d;
		vec2 hit = sphIntersect(p,d,s);

		if (hit.y >= 0. && hit.x >= 0.) {
			if (closestHit == -1 || closestHitDist > hit.x) {
				closestHitDist = hit.x;
				closestHit = i;
				continue;
			}
		}
	}

	return Hit(closestHit,closestHitDist);
}

#include "../rand.glsl"

vec3 shade(Ray r,int iter) {
	vec3 c = vec3(1.); // color for absorption
	vec3 e = vec3(0.); // emission

	int bounces = 3;
	Hit h;
	bool anyHit = false;
	for (int i=0;i<bounces;++i) {
		h = trace(r);

		// shade
		if (h.id != -1) {
			anyHit = true;
			vec3 pos = r.o + h.dist * r.d;
			vec3 n = normalize(pos-spheres[h.id].p);

			float w = spheres[h.id].r;
			vec3 nd;

			vec3 seed = pos + n * 1.4142 + vec3(UV, i) * 2.7182 + vec3(iter, u_time, -iter);
			vec3 rv = normalize(rand3Gauss(seed) * 2.0 - 1.0);
			
			rv=rv.zyx;
			nd = normalize(n + rv); // diff // already includes lambert cosine law

			vec3 ns = reflect(r.d,n); // spec
			vec3 nn = nd*(1.-w) + w*ns;
			
			float lc = 0.;
			//if (uv.x<.5)
				lc = 1.;
			//else
			//	lc = dot(n,nn)*2.; // add lambert cosine law to absorption

			int direct=0;

			vec3 mc = spheres[h.id].col; // mat color
			e += c*(mc*spheres[h.id].e); //TODO split into emission color and color
			c *= mc*lc; // absorb other wavelengths
			if (abs(pos.z) < 0.02)
				c *= vec3(0.,0.,1.);
			if (abs(pos.x) < 0.02)
				c *= vec3(1.,0.,0.);

			r = Ray(pos,nn);
		} else {
			float sunDirD = dot(normalize(vec3(1.,1.,1.)),r.d);
			sunDirD = max(0.,pow(sunDirD,100.));
			vec3 sunC = vec3(1.);
			float sunE = 0.;
			e += sunC*sunE*sunDirD; //TODO split into emission color and color
			break;
		}
	}

	// bg color
	if (!anyHit)
		e = vec3(.01);

	return e;
}

void main() {
	vec4 color=vec4(0.);
	//vec2 uv = gl_FragCoord.xy/u_resolution.xy;
	vec2 uv = (vec2(gl_GlobalInvocationID.xy)+.5)/u_resolution.xy;
	ivec2 texelCoord=ivec2(gl_GlobalInvocationID.xy);
	ivec2 imgSize = imageSize(u_outImg);
	if (texelCoord.x >= imgSize.x || texelCoord.y >= imgSize.y) {
		return;
	}

	//SEED = SEED*hash(u_time*(uv.x)+(uv.y));
	UV = uv;
	//UV.x = mod(UV.x,.5)*2.;
	vec2 ndc = UV * 2.0 - vec2(1.0);

	CAMPOS = u_cPos;
	CAMDIR = vec3(ndc.x,ndc.y,1.);
	CAMDIR = (u_m*normalize(vec4(CAMDIR,1.))).xyz;
	CAMDIR = normalize(CAMDIR);

	Ray r = {CAMPOS,CAMDIR};

#define ACC 1
#if ACC
	int samples = 1;
#else
	//spheres[0].p.x = sin(u_time)*2.;
	//spheres[0].p.z = cos(u_time)*2.;
	//spheres[0].p.y = 4.;
	int samples = 14;
#endif
	vec3 c = vec3(0.);
	for (int i=0;i<samples;++i) {
		c += shade(r,i);
	}
	c /= samples;

	if (u_frame==0)
		color = vec4(c,1.);
	else {
#if ACC
		if (u_camChange == 0.) {
			//color = vec4(c,1.)*.01+.99*texture(u_p,uv);
			//vec4 color2 = max(vec4(c,1.),texture(u_p,uv));
			//color = color*.98+color2*.02;

			float w = 1./(1.+u_frame);
			color = vec4(c,1.)*w + (1.-w)*texture(u_p,uv);

			//color = vec4(c,1.)+texture(u_p,uv);
			color.a = 1.;
		}
		else 
			color = vec4(c,1.)*.5+.5*texture(u_p,uv);
#else
		//color = vec4(c,1.)*.01+.99*texture(u_p,uv);
		color = vec4(c,1.);
#endif
	}

	imageStore(u_outImg,texelCoord,color);
};
