#version 460
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

#include "../bvh/bvhTraverse.glsl"

layout (std430, binding = 0) readonly buffer I0 { BVHNode node[]; } nodeData;
layout (std430, binding = 1) readonly buffer I1 { uint idx[]; } idxData;
layout (std430, binding = 2) readonly buffer I2 { vec4 tri[]; } triData;
DEFINE_TRAVERSE_FUNCTION(traverse_ailalaine,nodeData.node,idxData.idx,triData.tri,.xyz)

//layout (std430, binding = 3) writeonly buffer O { vec4 hit[]; } result;

layout(rgba32f, binding = 0) writeonly uniform image2D u_outImg;

uniform vec2 u_resolution;
uniform mat4 u_m;
uniform mat4 u_invVP;
uniform vec3 u_cPos;
uniform float u_time;

void main() {
	//uint id = gl_GlobalInvocationID.x;
	//if (id >= 1280 * 720) return; // out of bounds
	//if (id >= uint(r.x*r.y)) return; // out of bounds

	// convert thread id into screen coordinates
	//uint px = id % 1280, py = id / 1280;
	//float u = float( px ) / 1280.0f, v = float( py ) / 720.0f;

	// construct primary ray
	//const vec3 eye = vec3( 0.5, 0.5, -4 );
	//const vec3 view = vec3( 0, 0, 1 );
	//const vec3 C = eye + view;
	//const vec3 p1 = C + vec3( -1.6f, 1, 0 );
	//const vec3 p2 = C + vec3( 1.6f, 1, 0 );
	//const vec3 p3 = C + vec3( -1.6f, -1, 0 );
	//const vec3 P = p1 + u * (p2 - p1) + v * (p3 - p1);
	//const vec3 D = normalize( P - eye );
	//const vec3 rD = vec3( 1.0f / D.x, 1.0f / D.y, 1.0f / D.z );

	// trace
	//vec4 hit = traverse_ailalaine( eye, D, rD, 1e30f );
	//result.hit[id] = hit;

	vec2 uv = (vec2(gl_GlobalInvocationID.xy)+.5)/u_resolution.xy;
	ivec2 texelCoord=ivec2(gl_GlobalInvocationID.xy);

	ivec2 imgSize = imageSize(u_outImg);
	if (texelCoord.x >= imgSize.x || texelCoord.y >= imgSize.y) {
		return;
	}
	
	
	//TODO this is wrong if we consider aspect ratio
	vec2 ndc = uv * 2.0 - vec2(1.0);
	
	//vec3 camdir = vec3(ndc.x,ndc.y,1.);
	//camdir = (u_m*normalize(vec4(camdir,1.))).xyz;
	//camdir = normalize(camdir);

	// campos
	vec3 campos = u_cPos;
	mat4 invModel = inverse(u_m);
	campos = (invModel * vec4(u_cPos, 1.0)).xyz;

	// camdir
	vec4 targetWorld = u_invVP * vec4(ndc.x, ndc.y, -1.0, 1.0);
	targetWorld /= targetWorld.w; // Perspective divide
	vec3 camdir = normalize(targetWorld.xyz - u_cPos);
	camdir = normalize((invModel * vec4(camdir, 0.0)).xyz);

	vec3 rD = vec3(1.)/camdir;

	// (dist, u, v, triIdx)
	vec4 hit = traverse_ailalaine( campos, camdir, rD, 1e30f );
	
	//vec4 color = vec4(float(floatBitsToUint(hit.w))*0.00001,0.,0.,1.);
	vec4 color = vec4(hit.y,hit.z,0.,1.);
	imageStore(u_outImg,texelCoord,color);
}
